### ISSUE TITLE
json: cannot unmarshal string into Go struct field Options.evaluation_delay of type int

### ISSUE THREAD

**Issue by pdecat** [zorkian/go-datadog-api#111]
Unmarshalling monitors created or modified from the Datadog Web UI fails as `evaluation_delay` is returned by the Datadog API a string, not an int, the empty string meaning not defined/or zero (the datadog default.

The Datadog doc says (http://docs.datadoghq.com/api/?lang=console#monitors):

> evaluation_delay Time (in seconds) to delay evaluation, as a non-negative integer. For example, if the value is set to 300 (5min), the timeframe is set to last_5m and the time is 7:00, the monitor will evaluate data from 6:50 to 6:55. This is useful for AWS CloudWatch and other backfilled metrics to ensure the monitor will always have data during evaluation.

When not explicitly set, the API returns an empty string for the `evaluation_delay` field (appears as 0 in the datadog UI):

```
{"tags":["*"],"deleted":null,"query":"avg(last_5m):avg:docker.cpu.usage{*} > 0","message":"Test evaluation delay int or string","id":2363835,"multi":false,"name":"Test evaluation delay int or string","created":"2017-07-07T16:45:36.099033+00:00","created_at":1499445936000,"creator":{"id":543413,"handle":"me@myhost.com","name":null,"email":"me@myhost.com"},"org_id":113899,"modified":"2017-07-07T16:45:36.099033+00:00","state":{"groups":{}},"overall_state_modified":null,"overall_state":"No Data","type":"metric alert","options":{"notify_audit":false,"locked":false,"timeout_h":0,"silenced":{}
,"include_tags":false,"no_data_timeframe":10,"require_full_window":true,"new_host_delay":300,"notify_no_data":false,"renotify_interval":0,"evaluation_delay":"","escalation_message":"","thresholds":{"critical":0.0}}}
```

When set, the integer value in the `evaluation_delay` field is double-quoted:

```
{"tags":["*"],"deleted":null,"query":"avg(last_5m):avg:docker.cpu.usage{*} > 0","message":"Test evaluation delay int or string","id":2363835,"multi":false,"name":"Test evaluation delay int or string","created":"2017-07-07T16:45:36.099033+00:00","created_at":1499445936000,"creator": "id":543413,"handle":"me@myhost.com","name":null,"email":"me@myhost.com"},"org_id":113899,"modified":"2017-07-07T16:46:32.335298+00:00","state":{"groups":{}},"overall_state_modified":null,"overall_state":"No Data","type":"metric alert","options":{"notify_audit":false,"locked":false,"timeout_h":0,"silenced":{}
,"include_tags":false,"no_data_timeframe":10,"require_full_window":true,"new_host_delay":300,"notify_no_data":false,"renotify_interval":0,"evaluation_delay":"666","escalation_message":"","thresholds":{"critical":0.0}}}
```

Unfortunately, this breaks clients using go-datadog-api such as terraform with the following error:

```
* module.datadog.datadog_monitor.mymonitor: datadog_monitor.mymonitor: json: cannot unmarshal string into Go struct field Options.evaluation_delay of type int
```

The easiest way to trigger the issue is the edit the monitor from the Datadog Web UI.
Just saving a monitor without changing anything triggers it.

**Comment by pdecat** [comment]
Just noticed the addition of the documentation mentioned above was also contributed as PR to Datadog:  

https://github.com/DataDog/documentation/pull/1253/commits/f671301934e36ff08eb8516431e61882d2385315

**Comment by bshelton229** [comment]
@pdecat really sorry about that, it looks like something may have changed in the API. It was pretty difficult to get datadog to document this field in the API. We are also using terraform, and I'll bet our states would break if we tried to apply them now as well. We haven't done so in weeks.

As you noticed, we eventually submitted a PR against the documentation based on the behavior we were seeing from the API, and as part of a long standing open ticket with datadog.

I have a few test monitors in our account in a different terraform state. When I described these monitors -- which haven't been updated in a while -- with curl `evaluation_delay` it still comes back as an int. When you change any value in the datadog UI and re-submit the form, they start coming back as strings all of a sudden. I've been able to replicate this on a few monitors.

**Describing an existing monitor:**

```
.....
  "options": {
     ......
    "renotify_interval": 1440,
    "evaluation_delay": 920,
    "escalation_message": "RE-NOTIFY - Running low on EFS burst credits!"
  }
.....
```

**After changing the escalation message only and re-submitting the form via the datadog ui, this is the same monitor:**

```
...
  "options": {
    ...
    "renotify_interval": 1440,
    "evaluation_delay": "920",
    "escalation_message": "RE-NOTIFY - Running low on EFS burst credits CHANGED THIS ALONE!"
  }
...
```

I'll open a ticket with them and see where I get, it was a pretty slow process last time. It's definitely a string now, no question. Unless I'm going crazy (which is certainly possible) I remember it being an int before, and my old monitors still return int until they're updated. `renotify_interval` is an int, so I wonder if `evaluation_delay` being a string was intentional on datadog's end? They have not been good about updating the docs when they change the API, hence notification_delay remaining undocumented until we got it in there ourselves after a longstanding open ticket.

I'm opening a ticket right now to ask datadog about what they really want the type of this field to be and if this change was intentional. This is clearly a string now, so maybe we should change the type in the struct in this project; either that or wait to hear from datadog as to what it really should be. Maybe it being a string now is a mistake. So ultimately we need to figure out the right data type and reflect that in the go-datadog-api struct. We might also need to do some type checking and casting in the terraform provider to fix it. Something like this could possibly also go in the setter in this project, but I think that's generated from what I remember. For example, they're definitely coming back strings now, but my existing monitors are still coming back ints until they're updated via the UI, so it seems the API can return multiple types, so the terraform provider is probably the place to normalize that. My gut tells me if you sent an int via their rest api it will now convert it to a string, but that's something I'm going to try out today.

Sorry again. I'll dig in a little bit.

**Comment by pdecat** [comment]
Hi @bshelton229, thanks for the help on this issue.

The more I think about this issue, the more I believe the REST API is indeed being lazy.
Instead of waiting on Datadog to change this behavior, I have prepped a PR to handle this behavior on go-datadog-api where the unmarshalling takes place.

**Comment by bshelton229** [comment]
go-datadog-api does seem like the right place to fix this. I'm really new to go, it was really nice to see your solution to handling the ambiguous return. 

It really does seem to me that this is an unintended bug in the datadog API, and I'm hoping they fix it. `new_host_delay` is also documented as time in seconds, and when you set that as a string in the API, it casts it back to an int. Same thing with `no_data_timeframe`. I'll update this issue with the outcome of the datadog ticket I have open.

**Comment by pdecat** [comment]
Good point, I also believe the generic `IntOrString` type I implemented for `evaluation_delay` may be reused for  `no_data_timeframe`.
It has the added value of:
* being taken into account by the accessors generator,
* handling the empty string.

However, I did not touch it because the `UnmarshalJSON` for the `NoDataTimeframe` type compares the received value to `false` which is somewhat troubling and may need more investigation.

Regarding `new_host_delay`, it does not seem affected by the int/string discrepancy, yet.

**Comment by pdecat** [comment]
The `NoDataTimeframe` field was converted from `int` to `NoDataTimeframe` type by https://github.com/zorkian/go-datadog-api/pull/50 to fix https://github.com/zorkian/go-datadog-api/issues/49

It was afterward changed back to `int` in https://github.com/zorkian/go-datadog-api/pull/54/commits/3820f6674c30e8a9305c511b9826a3afdc031885

Then back to `NoDataTimeframe` type in https://github.com/zorkian/go-datadog-api/pull/55/commits/9285caba01f9ee8e6d079e99a7ffe0feb0aa4b70

Maybe `IntOrString` could be renamed into `LazyInt` and also handle the boolean cases...

**Comment by bshelton229** [comment]
I heard back from datadog, and the `new_host_delay` field is intended to be an INT and it ever being a string is a bug.

`After speaking with our engineers, I've learned it is meant to be an integer.  That the frontend sends it as a string is a bug.`

No ETA yet.

**Comment by bshelton229** [comment]
Datadog has resolved the issue. It looks good in my testing. When I create or update a monitor sending `evaluation_delay` as a string it comes back as an int everywhere. Updating in the UI also results in the field being an int. The field will not be present when not set.

From datadog:
```
An int is returned now, or no property at all if it is not set.  Thanks again for bringing this to our attention and let me know if you have any further questions or encounter any issues.
```

**Comment by pdecat** [comment]
Good news! Thanks again for your help on this issue.
