### ISSUE TITLE
Add more fields to Yaxis struct

### ISSUE THREAD

**Issue by NilsJPWerner** [zorkian/go-datadog-api#149]
Datadog has some extra y-axis options beyond min, max and scale: https://docs.datadoghq.com/graphing/miscellaneous/graphingjson/#y-axis-controls

There is also an unmentioned option `includeZero: bool`

Here is an example of allowed json:

```
"yaxis": {
    "scale": "log",
    "filter": {
         "top": "5%",
         "below": 15
     },
     units: "true",
     includeZero: "false"
}
```

**Comment by nyanshak** [comment]
I just raised #187 to support most of this ticket, except for filter. The reason I've not yet included filter is because I believe to support it properly will require custom (un)marshal because Datadog essentially overloaded filter so heavily.

```
"filter": 30     // just a number
"filter": "30"  // not sure, but this is probably also supported, same as 30 above
"filter": "5%" // a string with % sign
"filiter": {
    "top": "30%",
    "bottom": "10%"
    // or maybe... "below": 15 ? I don't see this in docs, but it's mentioned in this PR
}
```

I don't think I know enough about filters in Datadog to properly handle this, so I'm leaving it alone for now.

I'm closing this issue as #187 addresses most of it. Feel free to re-open a more specific issue to add support for yaxis.filter (and a PR if you like).
