### ISSUE TITLE
Invalid screen board JSON structure

### ISSUE THREAD

**Issue by seiffert** [zorkian/go-datadog-api#32]
I'm experiencing several issues with the screen boards API which was implemented in #13. From what I can tell, the screen board JSON documents that are being sent to DataDog are invalid. 
IMO the tests pass because the Datadog API is more or less a simple key-value store that saves everything you throw at it. However, I can't make it render screenboards created with the new data structure.

Compare those two JSON representations of the same widget:

The one that works (generated with the 'old' screen board code):

```
    {
      "title_size": 16,
      "title": true,
      "title_align": "left",
      "title_text": "# Containers",
      "height": 13,
      "tile_def": {
        "viz": "timeseries",
        "requests": [
          {
            "q": "...",
            "style": {
              "palette": "blue"
            },
            "type": "bars"
          }
        ],
        "events": [
          {
            "q": "tags:..."
          }
        ],
        "markers": []
      },
      "width": 36,
      "timeframe": "1d",
      "y": 5,
      "x": 111,
      "type": "timeseries",
      "legend": false
    }
```

vs. the one generated with the current go-datadog-api and the new Widget data structure. This one does not work:

```
    {
      "alert_graph": {},
      "iframe": {},
      "graph": {
        "tile_def": {}
      },
      "image": {
        "title_size": {
          "Auto": false,
          "Size": 0
        }
      },
      "alert_value": {},
      "change": {
        "tile_def": {}
      },
      "query_value": {
        "text_size": {
          "Auto": false,
          "Size": 0
        },
        "title_size": {
          "Auto": false,
          "Size": 0
        }
      },
      "hostmap": {
        "tile_def": {}
      },
      "free_text": {},
      "timeseries": {
        "title_size": {
          "Auto": false,
          "Size": 16
        },
        "title": true,
        "title_align": "left",
        "title_text": "# Containers",
        "height": 13,
        "tile_def": {
          "viz": "timeseries",
          "requests": [
            {
              "q": "...",
              "style": {
                "palette": "blue"
              },
              "type": "bars"
            }
          ],
          "events": [
            {
              "q": "tags:..."
            }
          ]
        },
        "width": 36,
        "timeframe": "1d",
        "y": 5,
        "x": 111,
        "type": "timeseries"
      },
      "check_status": {},
      "event_stream": {
        "title_size": {
          "Auto": false,
          "Size": 0
        }
      },
      "event_timeline": {},
      "frame": {},
      "toplist": {
        "tile_def": {},
        "title_size": {
          "Auto": false,
          "Size": 0
        }
      }
    }
```

Screenboards that have widgets in this 'new' syntax look like this when opening them via the UI:

![screenshot 2016-01-04 15 05 21](https://cloud.githubusercontent.com/assets/1111118/12091090/9c7f9e98-b2f4-11e5-9ebf-9b631ada240e.png)

The 'old' `Widget` structure was modelled after Datadog's API. I'm not sure how the new one can be mapped to the actual API without custom JSON marshalling code.

Also, the constructors I initially implemented in #7 where there to set the correct widget type. Now, one needs to pass the widget type every time a new widget is created:

```
widget := TimeseriesWidget{
  Type: "timeseries",

  X: x,
  Y: y,
   ...
}
```

Am I missing something here? Maybe @ojongerius can help out here? Thanks!

**Comment by ojongerius** [comment]
Sorry, did not have time for this,  and super busy working on other things. If anyone else wants to jump in; feel free to do so.

**Comment by kmshultz** [comment]
Hello @ojongerius! I'd like to help fix this so that we can get a `datadog_screenboard` provider written for Terraform.

As @seiffert mentioned, the Datadog API accepts pretty much any arbitrary JSON for widgets. Because of this, I propose doing away with all the by-type widget structs in favor of just the generic `Widget` struct, which would contain all valid options for all widget types.  Also, the testing in `integration/screen_widgets.go` is very comprehensive indeed, but since the API will accept it all anyway - or some widget with a key `'foo': 'bar'` - I'm not sure it's necessary at this time.

If you're open to this generic Widget option, I can work on a PR.

Thanks!

**Comment by ojongerius** [comment]
@kmshultz sorry I missed this comment 😞 

Would you still be willing to work on this? I'd be very happy with a more compact solution.

**Comment by rodrigorznd** [comment]
Hi @ojongerius, would you check my PR? it's my first go code, so i will be happy with any change request.

**Comment by ojongerius** [comment]
@rodrigorznd sorry mate, been busy with another project and will be travelling in the next couple of weeks.

Maybe @yfronto or @nyanshak have some time to review your code?

**Comment by oxlay** [comment]
Hello everyone, Datadog engineer here 👋 

Totally agree with @kmshultz, creating a single generic `Widget` type is I think the best approach here. And the integration tests are probably not meaningful in this particular case.

I created a PR (#168) which solves this issue with the mentioned approach.
It also removes outdated API attributes and adds support for newer widgets (such as the Service Summary, Monitor Summary, Log Stream or Uptime widgets).

Can one of the maintainers review it? 😄 

Also, our Terraform resources currently use this package, and we're baking a `datadog_screenboard` resource. We'll be able to ship it once this issue is resolved!

**Comment by nyanshak** [comment]
I'm concerned with not having any integration tests at all for screenboards. I'd like to have integration tests at least showing that we can create a widget with each of the fields, to validate that:

- a given field is actually accepted at all
- when that field has a value, the type passed to Datadog is accepted by Datadog's API
- Datadog's API returns values in the same type as expected

Ideally I'd like to go further and validate that the API won't accept other types (or if it does, it returns them as the expected type).

The reason I'm so concerned is getting burned with this:

- create timeboard through api with all the graphs as expected, through terraform
- user changes yaxis.min (or .max) through the UI
- UI sends string type "5" as the value
- Datadog API now returns yaxis.{min, max} as "5"
- Terraform fails when reading in the timeboard

We've since fixed the specific case I've referenced with PR #167, but it's just one example. The API is not versioned, breaking changes have come through unexpectedly in the past, and I'd at least like to be able to more easily isolate those problems with the integration tests.

Could you please add integration tests for the widgets?

---

That said... thank you so much for this PR! I'm really glad to have some Datadog engineers helping out on this (and the terraform provider).

**Comment by oxlay** [comment]
@nyanshak Thanks for the explanation, I understand the rationale.
I updated the PR with integration tests for all 19 widgets 😄

**Comment by nyanshak** [comment]
Closing after merging #168
